2021-02-21 08:18:28,270 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 2785194ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 08:22:23,018 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 212108ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 08:30:26,012 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 161986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 09:04:48,180 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 969844ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

