2021-02-21 00:00:00,959 INFO 13993 [egg-logrotator] agent logger reload: got log-reload message
2021-02-21 08:18:28,271 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 2785194ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 08:22:23,019 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 212108ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 08:30:26,013 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 161986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

2021-02-21 08:36:17,291 WARN 13993 [agent:development] reload worker because /Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/app/controller/user.ts change
2021-02-21 08:36:17,087 INFO 13993 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/app/controller/user.ts","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":80,"rdev":0,"blksize":4096,"ino":2514626,"size":1644,"blocks":8,"atimeMs":1613830587573.7156,"mtimeMs":1613867776974.2651,"ctimeMs":1613867776974.2651,"birthtimeMs":1606050625395.31,"atime":"2021-02-20T14:16:27.574Z","mtime":"2021-02-21T00:36:16.974Z","ctime":"2021-02-21T00:36:16.974Z","birthtime":"2020-11-22T13:10:25.395Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-21 09:04:48,189 ERROR 13993 nodejs.ClusterClientNoResponseError: client no response in 969844ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Volumes/Data/Files/ACM/Projects/YidianSaving/yi-dian-saving/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 13993
hostname: endaytrers-macbook.local

